/** @format */

import * as ec2 from "aws-cdk-lib/aws-ec2";
import { Construct } from "constructs";

export interface MinimalUserDataProps {
  envName: string;
  clusterName: string;
}

/**
 * Minimal UserData for Infrastructure Registration
 *
 * This construct creates a minimal user data script that ONLY handles:
 * 1. SSM agent installation and startup (required for Session Manager)
 * 2. ECS agent configuration and registration
 *
 * Goal: Get instance into ECS cluster ASAP
 *
 * Application setup (EFS, Prometheus, Grafana) is handled separately via:
 * - Lambda function triggered by ECS instance registration event
 * - SSM Run Command for application setup
 */
export class MinimalUserDataConstruct extends Construct {
  public readonly userData: ec2.UserData;

  constructor(scope: Construct, id: string, props: MinimalUserDataProps) {
    super(scope, id);

    // Create UserData object
    this.userData = ec2.UserData.forLinux();

    // Build minimal user data script
    this.userData.addCommands(
      "#!/bin/bash",
      "# ==========================================================================",
      `# MINIMAL USER DATA - ${props.envName.toUpperCase()}`,
      "# Purpose: Infrastructure Registration Only (SSM + ECS)",
      "# Application setup handled by Lambda + SSM Run Command",
      "# ==========================================================================",
      "",
      "# Enable logging",
      "exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1",
      "",
      "echo '========================================='",
      `echo 'Infrastructure Registration - ${props.envName}'`,
      "echo 'Timestamp:' $(date)",
      "echo '========================================='",
      "",
      "# ==========================================================================",
      "# IMDSv2 HELPER FUNCTIONS",
      "# ==========================================================================",
      "get_imds_token() {",
      '  local token=$(timeout 3 curl -X PUT "http://169.254.169.254/latest/api/token" \\',
      '    -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" \\',
      "    --connect-timeout 2 \\",
      "    --max-time 3 \\",
      "    --silent \\",
      '    --fail 2>/dev/null || echo "")',
      '  echo "$token"',
      "}",
      "",
      "imds_get() {",
      "  local path=$1",
      "  local token=$(get_imds_token)",
      '  if [ -z "$token" ]; then',
      '    echo ""',
      "    return 1",
      "  fi",
      '  timeout 3 curl -H "X-aws-ec2-metadata-token: $token" \\',
      "    --connect-timeout 2 \\",
      "    --max-time 3 \\",
      "    --silent \\",
      "    --fail \\",
      '    "http://169.254.169.254/latest/$path" 2>/dev/null || echo ""',
      "}",
      "",
      "# ==========================================================================",
      "# SSM AGENT INSTALLATION AND STARTUP",
      "# ==========================================================================",
      "echo 'Installing and starting SSM agent...'",
      "",
      "# Choose package manager (AL2023 uses dnf, AL2 uses yum)",
      "PKG_MGR=yum",
      "command -v dnf >/dev/null 2>&1 && PKG_MGR=dnf",
      "",
      "# Install SSM agent",
      "$PKG_MGR -y install amazon-ssm-agent || echo 'WARNING: SSM agent installation failed'",
      "",
      "# Enable and start SSM agent",
      "systemctl enable amazon-ssm-agent || true",
      "systemctl start amazon-ssm-agent || true",
      "",
      "# Verify SSM agent is running (with retries)",
      "SSM_RETRY_COUNT=0",
      "SSM_MAX_RETRIES=12", // 2 minutes total (10s * 12)
      "while [ $SSM_RETRY_COUNT -lt $SSM_MAX_RETRIES ]; do",
      "  if systemctl is-active amazon-ssm-agent >/dev/null 2>&1; then",
      "    echo '✓ SSM agent is running'",
      "    break",
      "  else",
      "    SSM_RETRY_COUNT=$((SSM_RETRY_COUNT + 1))",
      "    echo \"SSM agent not active yet (attempt $SSM_RETRY_COUNT/$SSM_MAX_RETRIES), waiting 10s...\"",
      "    systemctl start amazon-ssm-agent >/dev/null 2>&1 || true",
      "    sleep 10",
      "  fi",
      "done",
      "",
      "if ! systemctl is-active amazon-ssm-agent >/dev/null 2>&1; then",
      "  echo 'WARNING: SSM agent not active after $SSM_MAX_RETRIES attempts'",
      "else",
      "  echo '✓ SSM agent is running and ready for Session Manager'",
      "fi",
      "",
      "# ==========================================================================",
      "# ECS AGENT CONFIGURATION AND REGISTRATION",
      "# ==========================================================================",
      "echo 'Configuring ECS agent...'",
      "",
      "# Configure ECS cluster",
      `echo ECS_CLUSTER=${props.clusterName} >> /etc/ecs/ecs.config`,
      "echo ECS_ENABLE_CONTAINER_METADATA=true >> /etc/ecs/ecs.config",
      "echo ECS_ENABLE_TASK_IAM_ROLE=true >> /etc/ecs/ecs.config",
      "echo ECS_AWSVPC_BLOCK_IMDS=true >> /etc/ecs/ecs.config",
      "",
      "# Security: Block container access to IMDS",
      "if command -v iptables >/dev/null 2>&1; then",
      "  iptables --insert FORWARD 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP || true",
      "fi",
      "",
      "# Wait for IAM role to be attached",
      "echo 'Waiting for IAM role to be attached...'",
      'IAM_ROLE=""',
      "IAM_WAIT_COUNT=0",
      "IAM_MAX_WAITS=30", // 5 minutes total (10s * 30)
      "while [ $IAM_WAIT_COUNT -lt $IAM_MAX_WAITS ]; do",
      "  IAM_ROLE=$(imds_get meta-data/iam/security-credentials/)",
      '  if [ -n "$IAM_ROLE" ]; then',
      '    echo "✓ IAM role attached: $IAM_ROLE"',
      "    break",
      "  else",
      "    IAM_WAIT_COUNT=$((IAM_WAIT_COUNT + 1))",
      '    echo "Waiting for IAM role (attempt $IAM_WAIT_COUNT/$IAM_MAX_WAITS)..."',
      "    sleep 10",
      "  fi",
      "done",
      "",
      'if [ -z "$IAM_ROLE" ]; then',
      "  echo 'WARNING: IAM role not attached after $IAM_MAX_WAITS attempts'",
      "  echo 'ECS agent will be enabled but may not start until IAM role is attached'",
      "else",
      "  echo '✓ IAM role confirmed attached - proceeding with ECS agent startup'",
      "fi",
      "",
      "# Configure ECS agent service with retry logic",
      "echo 'Configuring ECS agent service...'",
      "mkdir -p /etc/systemd/system/ecs.service.d",
      "cat > /etc/systemd/system/ecs.service.d/override.conf << 'EOF'",
      "[Service]",
      "Restart=on-failure",
      "RestartSec=30",
      "StartLimitInterval=600",
      "StartLimitBurst=20",
      "EOF",
      "",
      "# Reload systemd",
      "systemctl daemon-reload",
      "",
      "# Enable ECS agent service",
      "echo 'Enabling ECS agent service...'",
      "systemctl enable ecs || echo 'WARNING: Failed to enable ECS service'",
      "",
      "# Start ECS agent",
      "echo 'Starting ECS agent...'",
      "# Use direct start method (avoids systemd wrapper issues on newer Linux distributions)",
      "# systemd service is still enabled for auto-start on boot, but we use direct start for reliability",
      "if [ -f /usr/libexec/amazon-ecs-init ]; then",
      "  echo 'Starting ECS agent directly via /usr/libexec/amazon-ecs-init start...'",
      "  if /usr/libexec/amazon-ecs-init start; then",
      "    echo '✓ ECS agent started successfully via direct method'",
      "  else",
      "    echo 'WARNING: Direct start failed, trying systemd as fallback...'",
      "    systemctl start ecs || echo 'ERROR: Both direct and systemd start methods failed'",
      "  fi",
      "else",
      "  echo 'WARNING: /usr/libexec/amazon-ecs-init not found, using systemd...'",
      "  systemctl start ecs || echo 'ERROR: systemctl start ecs failed'",
      "fi",
      "",
      "# Verify ECS agent is running (with retries)",
      "# Use process check instead of systemd status to avoid false negatives",
      "echo 'Verifying ECS agent is running...'",
      "RETRY_COUNT=0",
      "MAX_RETRIES=18", // 3 minutes total (10s * 18)
      "while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do",
      "  # Check if ECS agent process is running (more reliable than systemd status)",
      "  if pgrep -f 'ecs-agent' >/dev/null 2>&1; then",
      "    echo '✓ ECS agent process is running'",
      "    # Check if registered with cluster",
      "    if [ -f /var/log/ecs/ecs-agent.log ]; then",
      "      if grep -q 'Registered container instance' /var/log/ecs/ecs-agent.log 2>/dev/null; then",
      "        echo '✓ ECS agent has registered with cluster'",
      "      else",
      "        echo 'ECS agent running but not yet registered (this is normal, registration happens asynchronously)'",
      "      fi",
      "    fi",
      "    break",
      "  else",
      "    RETRY_COUNT=$((RETRY_COUNT + 1))",
      '    echo "ECS agent not running yet (attempt $RETRY_COUNT/$MAX_RETRIES), waiting 10s..."',
      "    # Retry with direct start method (more reliable)",
      "    /usr/libexec/amazon-ecs-init start >/dev/null 2>&1 || systemctl start ecs >/dev/null 2>&1 || true",
      "    sleep 10",
      "  fi",
      "done",
      "",
      "# ==========================================================================",
      "# COMPLETION MARKER",
      "# ==========================================================================",
      "",
      "# Create completion marker",
      "touch /var/lib/cloud/instance/infrastructure-registration-complete || true",
      "",
      "echo '========================================='",
      "echo '✓ Infrastructure registration completed!'",
      "echo 'Instance is ready for ECS tasks'",
      "echo 'Application setup will be handled by Lambda'",
      "echo 'Timestamp:' $(date)",
      "echo 'Log file: /var/log/user-data.log'",
      "echo '========================================='"
    );
  }
}

