/** @format */

import * as ec2 from "aws-cdk-lib/aws-ec2";
import { Construct } from "constructs";

export interface MinimalUserDataProps {
  envName: string;
  clusterName: string;
}

/**
 * Minimal UserData for Infrastructure Registration
 *
 * This construct creates a minimal user data script that ONLY handles:
 * 1. SSM agent installation and startup (required for Session Manager)
 * 2. ECS agent configuration and registration
 *
 * Goal: Get instance into ECS cluster ASAP
 *
 * Application setup (EFS, Prometheus, Grafana) is handled separately via:
 * - Lambda function triggered by ECS instance registration event
 * - SSM Run Command for application setup
 */
export class MinimalUserDataConstruct extends Construct {
  public readonly userData: ec2.UserData;

  constructor(scope: Construct, id: string, props: MinimalUserDataProps) {
    super(scope, id);

    // Create UserData object
    this.userData = ec2.UserData.forLinux();

    // Build minimal user data script
    this.userData.addCommands(
      "#!/bin/bash",
      "# ==========================================================================",
      `# MINIMAL USER DATA - ${props.envName.toUpperCase()}`,
      "# Purpose: Infrastructure Registration Only (SSM + ECS)",
      "# Application setup handled by Lambda + SSM Run Command",
      "# ==========================================================================",
      "",
      "# Enable logging",
      "exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1",
      "",
      "echo '========================================='",
      `echo 'Infrastructure Registration - ${props.envName}'`,
      "echo 'Timestamp:' $(date)",
      "echo '========================================='",
      "",
      "# ==========================================================================",
      "# IMDSv2 HELPER FUNCTIONS",
      "# ==========================================================================",
      "get_imds_token() {",
      '  local token=$(timeout 3 curl -X PUT "http://169.254.169.254/latest/api/token" \\',
      '    -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" \\',
      "    --connect-timeout 2 \\",
      "    --max-time 3 \\",
      "    --silent \\",
      '    --fail 2>/dev/null || echo "")',
      '  echo "$token"',
      "}",
      "",
      "imds_get() {",
      "  local path=$1",
      "  local token=$(get_imds_token)",
      '  if [ -z "$token" ]; then',
      '    echo ""',
      "    return 1",
      "  fi",
      '  timeout 3 curl -H "X-aws-ec2-metadata-token: $token" \\',
      "    --connect-timeout 2 \\",
      "    --max-time 3 \\",
      "    --silent \\",
      "    --fail \\",
      '    "http://169.254.169.254/latest/$path" 2>/dev/null || echo ""',
      "}",
      "",
      "# ==========================================================================",
      "# SSM AGENT INSTALLATION AND STARTUP",
      "# ==========================================================================",
      "echo 'Installing and starting SSM agent...'",
      "",
      "# Choose package manager (AL2023 uses dnf, AL2 uses yum)",
      "PKG_MGR=yum",
      "command -v dnf >/dev/null 2>&1 && PKG_MGR=dnf",
      "",
      "# Install SSM agent",
      "$PKG_MGR -y install amazon-ssm-agent || echo 'WARNING: SSM agent installation failed'",
      "",
      "# Enable and start SSM agent",
      "systemctl enable amazon-ssm-agent || true",
      "systemctl start amazon-ssm-agent || true",
      "",
      "# Verify SSM agent is running (with retries)",
      "SSM_RETRY_COUNT=0",
      "SSM_MAX_RETRIES=12", // 2 minutes total (10s * 12)
      "while [ $SSM_RETRY_COUNT -lt $SSM_MAX_RETRIES ]; do",
      "  if systemctl is-active amazon-ssm-agent >/dev/null 2>&1; then",
      "    echo '✓ SSM agent is running'",
      "    break",
      "  else",
      "    SSM_RETRY_COUNT=$((SSM_RETRY_COUNT + 1))",
      '    echo "SSM agent not active yet (attempt $SSM_RETRY_COUNT/$SSM_MAX_RETRIES), waiting 10s..."',
      "    systemctl start amazon-ssm-agent >/dev/null 2>&1 || true",
      "    sleep 10",
      "  fi",
      "done",
      "",
      "if ! systemctl is-active amazon-ssm-agent >/dev/null 2>&1; then",
      "  echo 'WARNING: SSM agent not active after $SSM_MAX_RETRIES attempts'",
      "else",
      "  echo '✓ SSM agent is running and ready for Session Manager'",
      "fi",
      "",
      "# ==========================================================================",
      "# ECS AGENT CONFIGURATION AND REGISTRATION",
      "# ==========================================================================",
      "echo 'Configuring ECS agent...'",
      "",
      "# Configure ECS cluster",
      `echo ECS_CLUSTER=${props.clusterName} >> /etc/ecs/ecs.config`,
      "echo ECS_ENABLE_CONTAINER_METADATA=true >> /etc/ecs/ecs.config",
      "echo ECS_ENABLE_TASK_IAM_ROLE=true >> /etc/ecs/ecs.config",
      "echo ECS_AWSVPC_BLOCK_IMDS=true >> /etc/ecs/ecs.config",
      "",
      "# Enable awslogs logging driver for CloudWatch Logs",
      "# Required for ECS tasks to send logs to CloudWatch Logs",
      '# Format: ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"]',
      'echo ECS_AVAILABLE_LOGGING_DRIVERS=[\\"json-file\\",\\"awslogs\\"] >> /etc/ecs/ecs.config',
      "",
      "# Security: Block container access to IMDS",
      "if command -v iptables >/dev/null 2>&1; then",
      "  iptables --insert FORWARD 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP || true",
      "fi",
      "",
      "# Wait for IAM role to be attached",
      "echo 'Waiting for IAM role to be attached...'",
      'IAM_ROLE=""',
      "IAM_WAIT_COUNT=0",
      "IAM_MAX_WAITS=30", // 5 minutes total (10s * 30)
      "while [ $IAM_WAIT_COUNT -lt $IAM_MAX_WAITS ]; do",
      "  IAM_ROLE=$(imds_get meta-data/iam/security-credentials/)",
      '  if [ -n "$IAM_ROLE" ]; then',
      '    echo "✓ IAM role attached: $IAM_ROLE"',
      "    break",
      "  else",
      "    IAM_WAIT_COUNT=$((IAM_WAIT_COUNT + 1))",
      '    echo "Waiting for IAM role (attempt $IAM_WAIT_COUNT/$IAM_MAX_WAITS)..."',
      "    sleep 10",
      "  fi",
      "done",
      "",
      'if [ -z "$IAM_ROLE" ]; then',
      "  echo 'WARNING: IAM role not attached after $IAM_MAX_WAITS attempts'",
      "  echo 'ECS agent will be enabled but may not start until IAM role is attached'",
      "else",
      "  echo '✓ IAM role confirmed attached - proceeding with ECS agent startup'",
      "fi",
      "",
      "# Configure ECS agent service with retry logic",
      "echo 'Configuring ECS agent service...'",
      "mkdir -p /etc/systemd/system/ecs.service.d",
      "cat > /etc/systemd/system/ecs.service.d/override.conf << 'EOF'",
      "[Service]",
      "Restart=on-failure",
      "RestartSec=30",
      "StartLimitInterval=600",
      "StartLimitBurst=20",
      "EOF",
      "",
      "# Reload systemd",
      "systemctl daemon-reload",
      "",
      "# Enable ECS agent service",
      "echo 'Enabling ECS agent service...'",
      "systemctl enable ecs || echo 'WARNING: Failed to enable ECS service'",
      "",
      "# Start ECS agent",
      "echo 'Starting ECS agent...'",
      "",
      "# Ensure Docker is running (required for ECS agent on AL2023)",
      "echo 'Ensuring Docker is running...'",
      "systemctl enable docker || true",
      "systemctl start docker || true",
      "if ! systemctl is-active docker >/dev/null 2>&1; then",
      "  echo 'WARNING: Docker is not running, waiting for it to start...'",
      "  DOCKER_RETRY=0",
      "  while [ $DOCKER_RETRY -lt 12 ]; do",
      "    if systemctl is-active docker >/dev/null 2>&1; then",
      "      echo '✓ Docker is running'",
      "      break",
      "    fi",
      "    DOCKER_RETRY=$((DOCKER_RETRY + 1))",
      '    echo "Waiting for Docker to start (attempt $DOCKER_RETRY/12)..."',
      "    systemctl start docker || true",
      "    sleep 5",
      "  done",
      "fi",
      "",
      "# Check if ecs-init is installed (should be pre-installed on ECS-optimized AMI)",
      "if [ ! -f /usr/libexec/amazon-ecs-init ]; then",
      "  echo 'ERROR: /usr/libexec/amazon-ecs-init not found!'",
      "  echo 'This should be pre-installed on ECS-optimized AMI'",
      "  echo 'Checking if ecs-init package is installed...'",
      "  PKG_MGR=yum",
      "  command -v dnf >/dev/null 2>&1 && PKG_MGR=dnf",
      "  $PKG_MGR list installed | grep -i ecs || echo 'ECS package not found'",
      "  echo 'Attempting to install ecs-init...'",
      "  $PKG_MGR install -y ecs-init || echo 'ERROR: Failed to install ecs-init'",
      "fi",
      "",
      "# Pre-pull ECS agent Docker image (required for AL2023)",
      "# The ecs-init script should do this, but we'll ensure it's done explicitly",
      "echo 'Pre-pulling ECS agent Docker image...'",
      "if command -v docker >/dev/null 2>&1; then",
      "  # Get the ECS agent image name from ecs-init",
      "  # For AL2023, it's typically: public.ecr.aws/aws-ecs/amazon-ecs-agent:latest",
      '  ECS_AGENT_IMAGE="public.ecr.aws/aws-ecs/amazon-ecs-agent:latest"',
      '  echo "Pulling ECS agent image: $ECS_AGENT_IMAGE"',
      "  if docker pull $ECS_AGENT_IMAGE 2>&1; then",
      "    echo '✓ ECS agent Docker image pulled successfully'",
      "  else",
      "    echo 'WARNING: Failed to pull ECS agent image, ecs-init will try again'",
      "    echo 'This may be due to network connectivity or ECR access issues'",
      "  fi",
      "else",
      "  echo 'WARNING: Docker command not found, cannot pre-pull image'",
      "fi",
      "",
      "# Verify ecs-init exists before attempting to start",
      "if [ -f /usr/libexec/amazon-ecs-init ]; then",
      "  echo '✓ Found /usr/libexec/amazon-ecs-init'",
      "",
      "  # CRITICAL: Pre-pull ECS agent Docker image before starting",
      "  # On AL2023, ECS agent runs as a Docker container and needs the image pulled first",
      "  echo 'Pre-pulling ECS agent Docker image (required for AL2023)...'",
      "  if command -v docker >/dev/null 2>&1 && systemctl is-active docker >/dev/null 2>&1; then",
      "    # The ECS agent image for AL2023 is in public ECR",
      '    ECS_AGENT_IMAGE="public.ecr.aws/aws-ecs/amazon-ecs-agent:latest"',
      '    echo "Pulling ECS agent image: $ECS_AGENT_IMAGE"',
      "    if docker pull $ECS_AGENT_IMAGE 2>&1; then",
      "      echo '✓ ECS agent Docker image pulled successfully'",
      "    else",
      "      echo 'WARNING: Failed to pull ECS agent image'",
      "      echo 'This may cause ECS agent startup to fail'",
      "      echo 'Checking network connectivity...'",
      "      curl -I https://public.ecr.aws 2>&1 | head -5 || echo 'Cannot reach ECR'",
      "    fi",
      "  else",
      "    echo 'WARNING: Docker is not running, cannot pre-pull image'",
      "    echo 'ECS agent startup may fail with \"no such image\" error'",
      "  fi",
      "",
      "  echo 'Starting ECS agent directly via /usr/libexec/amazon-ecs-init start...'",
      "  if /usr/libexec/amazon-ecs-init start 2>&1; then",
      "    echo '✓ ECS agent started successfully via direct method'",
      "  else",
      "    echo 'ERROR: Direct start failed, checking logs...'",
      "    # Check ecs-init logs (different from ecs-agent.log)",
      "    if [ -f /var/log/ecs/ecs-init.log ]; then",
      "      echo 'Last 20 lines of ecs-init log:'",
      "      tail -20 /var/log/ecs/ecs-init.log || true",
      "    fi",
      "    if [ -f /var/log/ecs/ecs-agent.log ]; then",
      "      echo 'Last 20 lines of ECS agent log:'",
      "      tail -20 /var/log/ecs/ecs-agent.log || true",
      "    fi",
      "    echo 'Trying systemd as fallback...'",
      "    systemctl start ecs 2>&1 || {",
      "      echo 'ERROR: Both direct and systemd start methods failed'",
      "      echo 'Checking systemd status...'",
      "      systemctl status ecs || true",
      "      echo 'Checking journalctl logs...'",
      "      journalctl -u ecs -n 20 --no-pager || true",
      "    }",
      "  fi",
      "else",
      "  echo 'ERROR: /usr/libexec/amazon-ecs-init still not found after installation attempt'",
      "  echo 'Trying systemd as last resort...'",
      "  systemctl start ecs 2>&1 || {",
      "    echo 'ERROR: systemctl start ecs failed'",
      "    systemctl status ecs || true",
      "    journalctl -u ecs -n 20 --no-pager || true",
      "  }",
      "fi",
      "",
      "# Verify ECS agent is running (with retries)",
      "# Use process check instead of systemd status to avoid false negatives",
      "echo 'Verifying ECS agent is running...'",
      "RETRY_COUNT=0",
      "MAX_RETRIES=18", // 3 minutes total (10s * 18)
      "while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do",
      "  # Check if ECS agent process is running (more reliable than systemd status)",
      "  if pgrep -f 'ecs-agent' >/dev/null 2>&1; then",
      "    echo '✓ ECS agent process is running'",
      "    # Check if registered with cluster",
      "    if [ -f /var/log/ecs/ecs-agent.log ]; then",
      "      if grep -q 'Registered container instance' /var/log/ecs/ecs-agent.log 2>/dev/null; then",
      "        echo '✓ ECS agent has registered with cluster'",
      "      else",
      "        echo 'ECS agent running but not yet registered (this is normal, registration happens asynchronously)'",
      "      fi",
      "    fi",
      "    break",
      "  else",
      "    RETRY_COUNT=$((RETRY_COUNT + 1))",
      '    echo "ECS agent not running yet (attempt $RETRY_COUNT/$MAX_RETRIES), waiting 10s..."',
      "    # Check systemd status for more details",
      "    if systemctl is-failed ecs >/dev/null 2>&1; then",
      "      echo 'ECS service is in failed state, checking logs...'",
      "      journalctl -u ecs -n 10 --no-pager || true",
      "      if [ -f /var/log/ecs/ecs-agent.log ]; then",
      "        echo 'Last 20 lines of ECS agent log:'",
      "        tail -20 /var/log/ecs/ecs-agent.log || true",
      "      fi",
      "      echo 'Attempting to reset failed state and restart...'",
      "      systemctl reset-failed ecs || true",
      "    fi",
      "    # Retry with direct start method (more reliable)",
      "    if [ -f /usr/libexec/amazon-ecs-init ]; then",
      "      /usr/libexec/amazon-ecs-init start >/dev/null 2>&1 || systemctl start ecs >/dev/null 2>&1 || true",
      "    else",
      "      systemctl start ecs >/dev/null 2>&1 || true",
      "    fi",
      "    sleep 10",
      "  fi",
      "done",
      "",
      "# Final verification - if still not running, show diagnostic info",
      "if ! pgrep -f 'ecs-agent' >/dev/null 2>&1; then",
      "  echo 'WARNING: ECS agent is still not running after $MAX_RETRIES attempts'",
      "  echo 'Diagnostic information:'",
      "  echo '--- Systemd status ---'",
      "  systemctl status ecs --no-pager || true",
      "  echo '--- Journalctl logs ---'",
      "  journalctl -u ecs -n 30 --no-pager || true",
      "  echo '--- ECS config file ---'",
      "  cat /etc/ecs/ecs.config || true",
      "  echo '--- Checking for ecs-init ---'",
      "  ls -la /usr/libexec/amazon-ecs-init || echo 'ecs-init not found'",
      "  echo '--- Checking IAM role ---'",
      "  imds_get meta-data/iam/security-credentials/ || echo 'IAM role check failed'",
      "  echo 'ERROR: ECS agent failed to start. Manual intervention required.'",
      "else",
      "  echo '✓ ECS agent verification complete'",
      "fi",
      "",
      "# ==========================================================================",
      "# COMPLETION MARKER",
      "# ==========================================================================",
      "",
      "# Create completion marker",
      "touch /var/lib/cloud/instance/infrastructure-registration-complete || true",
      "",
      "echo '========================================='",
      "echo '✓ Infrastructure registration completed!'",
      "echo 'Instance is ready for ECS tasks'",
      "echo 'Application setup will be handled by Lambda'",
      "echo 'Timestamp:' $(date)",
      "echo 'Log file: /var/log/user-data.log'",
      "echo '========================================='"
    );
  }
}
