/** @format */

import * as autoscaling from "aws-cdk-lib/aws-autoscaling";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as s3_assets from "aws-cdk-lib/aws-s3-assets";
import { Construct } from "constructs";

import { CrossAccountTarget } from "../../../types";

export interface MonitoringUserDataProps {
  envName: string;
  region: string;

  // EFS Configuration
  fileSystemId: string;
  efsStackName: string;

  // ECS Configuration
  clusterName: string;

  // S3 Assets (optional - for ECS stack compatibility)
  prometheusAsset?: s3_assets.Asset;
  grafanaAsset?: s3_assets.Asset;
  dashboardsAsset?: s3_assets.Asset;

  // Cross-account targets (optional)
  crossAccountTargets?: CrossAccountTarget[];

  // Feature flags
  enableEfsMount?: boolean;
  enableEcsAgent?: boolean;
  enableS3Assets?: boolean;
}

/**
 * Centralized UserData Management for Monitoring Infrastructure
 *
 * This construct consolidates all UserData logic into a single, maintainable location.
 * It eliminates conflicts between multiple stacks trying to manage UserData.
 *
 * Features:
 * - EFS mounting and setup
 * - ECS agent configuration
 * - S3 asset downloads (optional)
 * - Cross-account monitoring setup
 * - Comprehensive error handling and logging
 * - Modular design for different deployment scenarios
 */
export class MonitoringUserDataConstruct extends Construct {
  private readonly userDataCommands: string[] = [];
  public readonly userData: ec2.UserData;

  constructor(scope: Construct, id: string, props: MonitoringUserDataProps) {
    super(scope, id);

    // Create UserData object
    this.userData = ec2.UserData.forLinux();

    // Build UserData script in logical sections
    this.addScriptHeader(props.envName);

    if (props.enableEfsMount !== false) {
      this.addEfsSetup(props);
    }

    if (props.enableS3Assets && props.prometheusAsset) {
      this.addS3AssetDownloads(props);
    }

    if (props.enableEcsAgent !== false) {
      this.addEcsConfiguration(props.clusterName);
    }

    this.addScriptFooter();

    // Add all commands to the UserData object
    this.userData.addCommands(...this.userDataCommands);
  }

  /**
   * Apply UserData to an Auto Scaling Group
   * @deprecated Use the userData property directly instead
   */
  public applyToAutoScalingGroup(asg: autoscaling.AutoScalingGroup): void {
    asg.addUserData(...this.userDataCommands);
  }

  /**
   * Get UserData commands as array (for testing/debugging)
   */
  public getUserDataCommands(): string[] {
    return [...this.userDataCommands];
  }

  /**
   * Script header with logging setup
   */
  private addScriptHeader(envName: string): void {
    this.userDataCommands.push(
      "#!/bin/bash",
      "set -e",
      "",
      "# ==========================================================================",
      `# MONITORING INFRASTRUCTURE SETUP - ${envName.toUpperCase()}`,
      "# Generated by MonitoringUserDataConstruct",
      "# ==========================================================================",
      "",
      "# Enable detailed logging",
      "exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1",
      "",
      `echo '========================================='`,
      `echo 'Monitoring Setup Started - ${envName}'`,
      "echo 'Timestamp:' $(date)",
      `echo '========================================='`,
      ""
    );
  }

  /**
   * EFS mounting and directory setup with enhanced error handling
   */
  private addEfsSetup(props: MonitoringUserDataProps): void {
    this.userDataCommands.push(
      "# ==========================================================================",
      "# EFS SETUP WITH ENHANCED ERROR HANDLING",
      "# ==========================================================================",
      "",
      "echo 'Installing EFS utilities...'",
      "yum update -y",
      "yum install -y amazon-efs-utils awscli",
      "",
      "# Verify installations",
      "aws --version",
      "mount.efs --help >/dev/null 2>&1 && echo '✓ EFS mount helper available'",
      "",
      "# Configure EFS utils",
      "cat > /etc/efs-utils.conf << 'EOF'",
      "[mount]",
      `region = ${props.region}`,
      "iam = true",
      "tls = true",
      "rsize = 1048576",
      "wsize = 1048576",
      "hard = true",
      "intr = true",
      "timeo = 600",
      "retrans = 2",
      "EOF",
      "",
      "# Mount EFS with retry logic",
      "mkdir -p /mnt/efs",
      "MOUNT_RETRIES=5",
      "for i in $(seq 1 $MOUNT_RETRIES); do",
      `  echo "EFS mount attempt $i of $MOUNT_RETRIES"`,
      `  if timeout 90 mount -t efs -o tls,iam ${props.fileSystemId}:/ /mnt/efs; then`,
      "    echo '✓ EFS mounted successfully'",
      "    break",
      "  else",
      "    echo 'Mount failed, retrying in 10 seconds...'",
      "    [ $i -eq $MOUNT_RETRIES ] && { echo 'ERROR: EFS mount failed'; exit 1; }",
      "    sleep 10",
      "  fi",
      "done",
      "",
      "# Verify EFS mount is working",
      "if ! mountpoint -q /mnt/efs; then",
      "  echo 'ERROR: EFS is not properly mounted'",
      "  exit 1",
      "fi",
      "",
      "# Add to fstab for persistence",
      `echo "${props.fileSystemId}:/ /mnt/efs efs defaults,_netdev,tls,iam 0 0" >> /etc/fstab`,
      "",
      "# ==========================================================================",
      "# EFS DIRECTORY STRUCTURE SETUP - USING EXACT WORKING COMMANDS",
      "# ==========================================================================",
      "",
      "echo 'Setting up EFS directory structure using confirmed working commands...'",
      "",
      "# Create directories in EFS (exact commands that worked manually)",
      "sudo mkdir -p /mnt/efs/prometheus-data",
      "sudo mkdir -p /mnt/efs/grafana-data",
      "sudo mkdir -p /mnt/efs/config/prometheus",
      "sudo mkdir -p /mnt/efs/config/grafana/provisioning/datasources",
      "sudo mkdir -p /mnt/efs/config/grafana/provisioning/dashboards",
      "sudo mkdir -p /mnt/efs/config/grafana/dashboards",
      "",
      "# Set base permissions first",
      "sudo chown -R root:root /mnt/efs/",
      "sudo chmod -R 755 /mnt/efs/",
      "",
      "# ==========================================================================",
      "# CONTAINER-SPECIFIC PERMISSIONS FIX",
      "# ==========================================================================",
      "",
      "echo 'Setting container-specific permissions...'",
      "",
      "# Prometheus runs as UID 65534 (nobody) - set ownership for data and config",
      "sudo chown -R 65534:65534 /mnt/efs/prometheus-data",
      "sudo chown -R 65534:65534 /mnt/efs/config/prometheus",
      "sudo chmod -R 755 /mnt/efs/prometheus-data",
      "sudo chmod -R 755 /mnt/efs/config/prometheus",
      "",
      "# Grafana runs as UID 472 (grafana) - set ownership for data and config",
      "sudo chown -R 472:472 /mnt/efs/grafana-data",
      "sudo chown -R 472:472 /mnt/efs/config/grafana",
      "sudo chmod -R 755 /mnt/efs/grafana-data",
      "sudo chmod -R 755 /mnt/efs/config/grafana",
      "",
      "# Ensure Grafana can write to its data directories (some need 777 for plugins/logs)",
      "sudo chmod -R 777 /mnt/efs/grafana-data",
      "",
      "echo '✓ Container-specific permissions set'",
      "echo '✓ EFS directory structure created with working commands'",
      "",
      "# ==========================================================================",
      "# CONFIGURATION FILES - ALWAYS CREATE WORKING CONFIGS",
      "# ==========================================================================",
      "",
      "echo 'Creating monitoring configuration files...'",
      "",
      "# Always create working configuration files (don't rely on Lambda/SSM)",
      "# This ensures containers can start even if Lambda initialization fails",
      "",
      "# Create basic Prometheus config",
      "cat > /mnt/efs/config/prometheus/prometheus.yml << 'EOF'",
      "global:",
      "  scrape_interval: 15s",
      "  evaluation_interval: 15s",
      "  external_labels:",
      `    environment: '${props.envName}'`,
      `    region: '${props.region}'`,
      "",
      "scrape_configs:",
      "  - job_name: 'prometheus'",
      "    static_configs:",
      "      - targets: ['localhost:9090']",
      "    scrape_interval: 15s",
      "    metrics_path: '/prometheus/metrics'",
      "",
      "  - job_name: 'node-exporter'",
      "    static_configs:",
      "      - targets: ['localhost:9100']",
      "    scrape_interval: 15s",
      "",
      "  - job_name: 'grafana'",
      "    static_configs:",
      "      - targets: ['localhost:3000']",
      "    scrape_interval: 30s",
      "    metrics_path: '/metrics'",
      "EOF",
      "",
      "# Note: Grafana datasource config is created by EFS initialization Lambda",
      "# This ensures no conflicts with multiple default datasources",
      "",
      "# Create dashboard provisioning config",
      "cat > /mnt/efs/config/grafana/provisioning/dashboards/dashboards.yml << 'EOF'",
      "apiVersion: 1",
      "providers:",
      "  - name: 'Default'",
      "    orgId: 1",
      "    folder: ''",
      "    type: file",
      "    disableDeletion: false",
      "    updateIntervalSeconds: 10",
      "    allowUiUpdates: true",
      "    options:",
      "      path: /mnt/grafana-dashboards",
      "EOF",
      "",
      "# Create a basic dashboard for immediate functionality",
      "cat > /mnt/efs/config/grafana/dashboards/system-overview.json << 'EOF'",
      "{",
      '  "dashboard": {',
      '    "id": null,',
      '    "title": "System Overview",',
      '    "tags": ["system", "monitoring"],',
      '    "timezone": "browser",',
      '    "panels": [',
      "      {",
      '        "id": 1,',
      '        "title": "Prometheus Targets",',
      '        "type": "stat",',
      '        "targets": [',
      "          {",
      '            "expr": "up",',
      '            "legendFormat": "{{job}} - {{instance}}"',
      "          }",
      "        ],",
      '        "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}',
      "      }",
      "    ],",
      '    "time": {"from": "now-1h", "to": "now"},',
      '    "refresh": "30s"',
      "  }",
      "}",
      "EOF",
      "",
      "# Set proper ownership for all config files",
      "sudo chown 65534:65534 /mnt/efs/config/prometheus/prometheus.yml",
      "# Note: prometheus.yml ownership is handled by EFS initialization Lambda",
      "sudo chown 472:472 /mnt/efs/config/grafana/provisioning/dashboards/dashboards.yml",
      "sudo chown 472:472 /mnt/efs/config/grafana/dashboards/system-overview.json",
      "",
      "# Verify configuration files were created",
      "echo 'Verifying configuration files:'",
      "ls -la /mnt/efs/config/prometheus/",
      "ls -la /mnt/efs/config/grafana/provisioning/datasources/ || echo 'Datasources managed by EFS Lambda'",
      "ls -la /mnt/efs/config/grafana/provisioning/dashboards/",
      "ls -la /mnt/efs/config/grafana/dashboards/",
      "",
      "echo '✓ Configuration files created successfully'",
      "",
      "# ==========================================================================",
      "# OPTIONAL: TRY TO ENHANCE WITH LAMBDA-GENERATED CONFIGS",
      "# ==========================================================================",
      "",
      "echo 'Attempting to enhance with Lambda-generated configurations...'",
      "",
      "# Try to get enhanced configs from SSM (non-blocking)",
      `if aws ssm get-parameter --region ${props.region} --name "/monitoring/${props.efsStackName}/prometheus-config" --query "Parameter.Value" --output text > /tmp/enhanced-prometheus.yml 2>/dev/null; then`,
      "  echo '✓ Enhanced Prometheus config found, applying...'",
      "  cp /tmp/enhanced-prometheus.yml /mnt/efs/config/prometheus/prometheus.yml",
      "  sudo chown 65534:65534 /mnt/efs/config/prometheus/prometheus.yml",
      "  echo '✓ Enhanced Prometheus config applied'",
      "else",
      "  echo 'ℹ Enhanced Prometheus config not available, using basic config'",
      "fi",
      "",
      "# Enhanced Grafana datasource config is handled by EFS initialization Lambda",
      "echo 'ℹ Grafana datasource config managed by EFS Lambda - no manual override needed'",
      "",
      "# ==========================================================================",
      "# CREATE SYMLINKS - USING EXACT WORKING COMMANDS",
      "# ==========================================================================",
      "",
      "echo 'Creating symlinks using confirmed working commands...'",
      "",
      "# Create symlinks (exact commands that worked manually)",
      "sudo ln -sf /mnt/efs/prometheus-data /mnt/prometheus-data",
      "sudo ln -sf /mnt/efs/grafana-data /mnt/grafana-data",
      "sudo ln -sf /mnt/efs/config/prometheus /mnt/prometheus-config",
      "sudo ln -sf /mnt/efs/config/grafana/provisioning /mnt/grafana-provisioning",
      "sudo ln -sf /mnt/efs/config/grafana/dashboards /mnt/grafana-dashboards",
      "",
      "# Verify symlinks were created correctly",
      "echo 'Verifying symlinks:'",
      "ls -la /mnt/ | grep -E '(prometheus|grafana)'",
      "",
      "# Verify EFS directory structure",
      "echo 'Verifying EFS directory structure:'",
      "ls -la /mnt/efs/",
      "ls -la /mnt/efs/config/ 2>/dev/null || echo 'Config directory not found'",
      "",
      "# Final verification - ensure symlinks point to EFS",
      "for link in prometheus-data grafana-data prometheus-config grafana-provisioning grafana-dashboards; do",
      '  if [ -L "/mnt/$link" ]; then',
      '    echo "✓ /mnt/$link -> $(readlink /mnt/$link)"',
      "  else",
      '    echo "✗ /mnt/$link is not a symlink!"',
      "    exit 1",
      "  fi",
      "done",
      "",
      "echo '✓ EFS setup completed successfully'",
      ""
    );
  }

  /**
   * S3 asset downloads and processing (for ECS stack compatibility)
   */
  private addS3AssetDownloads(props: MonitoringUserDataProps): void {
    if (
      !props.prometheusAsset ||
      !props.grafanaAsset ||
      !props.dashboardsAsset
    ) {
      return;
    }

    this.userDataCommands.push(
      "# ==========================================================================",
      "# S3 ASSET DOWNLOADS",
      "# ==========================================================================",
      "",
      "echo 'Downloading configuration assets from S3...'",
      "",
      "# Download Prometheus config",
      `aws s3 cp s3://${props.prometheusAsset.s3BucketName}/${props.prometheusAsset.s3ObjectKey} /tmp/prometheus-config.zip --region ${props.region}`,
      "unzip -o /tmp/prometheus-config.zip -d /tmp/prometheus-config",
      "",
      "# Download Grafana provisioning",
      `aws s3 cp s3://${props.grafanaAsset.s3BucketName}/${props.grafanaAsset.s3ObjectKey} /tmp/grafana-provisioning.zip --region ${props.region}`,
      "unzip -o /tmp/grafana-provisioning.zip -d /tmp/grafana-provisioning",
      "",
      "# Download Grafana dashboards",
      `aws s3 cp s3://${props.dashboardsAsset.s3BucketName}/${props.dashboardsAsset.s3ObjectKey} /tmp/grafana-dashboards.zip --region ${props.region}`,
      "unzip -o /tmp/grafana-dashboards.zip -d /tmp/grafana-dashboards",
      "",
      "# Process and copy configs",
      "mkdir -p /mnt/prometheus-config /mnt/grafana-provisioning /mnt/grafana-dashboards",
      "",
      "# Copy processed configs to mount points",
      "find /tmp/prometheus-config -name '*.yml' -exec cp {} /mnt/prometheus-config/ \\;",
      "find /tmp/grafana-provisioning -name '*.yml' -exec cp {} /mnt/grafana-provisioning/ \\;",
      "find /tmp/grafana-dashboards -name '*.json' -exec cp {} /mnt/grafana-dashboards/ \\;",
      "",
      "echo '✓ S3 assets processed'",
      ""
    );

    // Add cross-account config injection if provided
    if (props.crossAccountTargets && props.crossAccountTargets.length > 0) {
      this.addCrossAccountConfig(props.crossAccountTargets);
    }
  }

  /**
   * Cross-account monitoring configuration
   */
  private addCrossAccountConfig(targets: CrossAccountTarget[]): void {
    this.userDataCommands.push(
      "# Cross-account monitoring targets",
      "echo 'Configuring cross-account monitoring...'",
      "cat >> /mnt/prometheus-config/prometheus.yml << 'EOF'"
    );

    // Generate Prometheus scrape configs
    targets.forEach((target) => {
      this.userDataCommands.push(
        "",
        `  # ${target.envName} - ${target.targetType}`,
        `  - job_name: '${target.targetType}-${target.envName}'`,
        target.metricsPath ? `    metrics_path: '${target.metricsPath}'` : "",
        "    static_configs:",
        "      - targets:",
        `          - '${target.privateIp}:${target.port}'`,
        "        labels:",
        `          environment: '${target.envName}'`,
        `          service: '${target.targetType}'`,
        "          source: 'cross-account'"
      );
    });

    this.userDataCommands.push(
      "EOF",
      "echo '✓ Cross-account targets configured'",
      ""
    );
  }

  /**
   * ECS agent configuration and startup
   */
  private addEcsConfiguration(clusterName: string): void {
    this.userDataCommands.push(
      "# ==========================================================================",
      "# ECS AGENT CONFIGURATION",
      "# ==========================================================================",
      "",
      "echo 'Configuring ECS agent...'",
      "",
      "# Configure ECS cluster",
      `echo ECS_CLUSTER=${clusterName} >> /etc/ecs/ecs.config`,
      "echo ECS_AWSVPC_BLOCK_IMDS=true >> /etc/ecs/ecs.config",
      "",
      "# Security: Block container access to IMDS",
      "iptables --insert FORWARD 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP",
      "service iptables save",
      "",
      "# Start and enable ECS agent",
      "systemctl start ecs",
      "systemctl enable ecs",
      "",
      "# Verify ECS agent is running",
      "sleep 10",
      "systemctl is-active ecs && echo '✓ ECS agent is running' || { echo 'ERROR: ECS agent failed to start'; exit 1; }",
      ""
    );
  }

  /**
   * Script footer with completion marker
   */
  private addScriptFooter(): void {
    this.userDataCommands.push(
      "# ==========================================================================",
      "# SETUP COMPLETION",
      "# ==========================================================================",
      "",
      "# Create completion marker",
      "touch /var/lib/cloud/instance/monitoring-setup-complete",
      "",
      "echo '========================================='",
      "echo '✓ Monitoring setup completed successfully!'",
      "echo 'Timestamp:' $(date)",
      "echo 'Log file: /var/log/user-data.log'",
      "echo '========================================='",
      ""
    );
  }
}
