/** @format */

import * as autoscaling from "aws-cdk-lib/aws-autoscaling";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as s3_assets from "aws-cdk-lib/aws-s3-assets";
import { Construct } from "constructs";

import { CrossAccountTarget } from "../../../types";

export interface MonitoringUserDataProps {
  envName: string;
  region: string;

  // EFS Configuration
  fileSystemId: string;
  efsStackName: string;

  // ECS Configuration
  clusterName: string;

  // S3 Assets (optional - for ECS stack compatibility)
  prometheusAsset?: s3_assets.Asset;
  grafanaAsset?: s3_assets.Asset;
  dashboardsAsset?: s3_assets.Asset;

  // Cross-account targets (optional)
  crossAccountTargets?: CrossAccountTarget[];

  // Feature flags
  enableEfsMount?: boolean;
  enableEcsAgent?: boolean;
  enableS3Assets?: boolean;
}

/**
 * Centralized UserData Management for Monitoring Infrastructure
 *
 * This construct consolidates all UserData logic into a single, maintainable location.
 * It eliminates conflicts between multiple stacks trying to manage UserData.
 *
 * Features:
 * - EFS mounting and setup
 * - ECS agent configuration
 * - S3 asset downloads (optional)
 * - Cross-account monitoring setup
 * - Comprehensive error handling and logging
 * - Modular design for different deployment scenarios
 */
export class MonitoringUserDataConstruct extends Construct {
  private readonly userDataCommands: string[] = [];
  public readonly userData: ec2.UserData;

  constructor(scope: Construct, id: string, props: MonitoringUserDataProps) {
    super(scope, id);

    // Create UserData object
    this.userData = ec2.UserData.forLinux();

    // Build UserData script in logical sections
    this.addScriptHeader(props.envName);

    if (props.enableS3Assets && props.prometheusAsset) {
      this.addS3AssetDownloads(props);
    }

    if (props.enableEcsAgent !== false) {
      this.addEcsConfiguration(props.clusterName);
    }

    // IMPORTANT: EFS setup can fail transiently (DNS, network, mount targets not ready).
    // We intentionally run ECS agent configuration BEFORE EFS mounting so the instance
    // still registers into the cluster even if EFS mount needs retries.
    if (props.enableEfsMount !== false) {
      this.addEfsSetup(props);
    }

    this.addScriptFooter();

    // Add all commands to the UserData object
    this.userData.addCommands(...this.userDataCommands);
  }

  /**
   * Apply UserData to an Auto Scaling Group
   * @deprecated Use the userData property directly instead
   */
  public applyToAutoScalingGroup(asg: autoscaling.AutoScalingGroup): void {
    asg.addUserData(...this.userDataCommands);
  }

  /**
   * Get UserData commands as array (for testing/debugging)
   */
  public getUserDataCommands(): string[] {
    return [...this.userDataCommands];
  }

  /**
   * Script header with logging setup
   */
  private addScriptHeader(envName: string): void {
    this.userDataCommands.push(
      "#!/bin/bash",
      "# NOTE: set -e is NOT used - we want the script to continue even if some steps fail",
      "# This allows ECS agent and EFS mounting to retry later if they fail initially",
      "",
      "# ==========================================================================",
      `# MONITORING INFRASTRUCTURE SETUP - ${envName.toUpperCase()}`,
      "# Generated by MonitoringUserDataConstruct",
      "# ==========================================================================",
      "",
      "# Enable detailed logging",
      "exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1",
      "",
      "# ==========================================================================",
      "# IMDSv2 HELPER FUNCTIONS",
      "# ==========================================================================",
      "# Since launch template requires IMDSv2 (HttpTokens=required), all IMDS calls",
      "# must use token-based authentication. IMDSv1 calls will hang/timeout.",
      "",
      "# Get IMDSv2 token (with timeout to prevent hanging)",
      "get_imds_token() {",
      '  local token=$(timeout 3 curl -X PUT "http://169.254.169.254/latest/api/token" \\',
      '    -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" \\',
      "    --connect-timeout 2 \\",
      "    --max-time 3 \\",
      "    --silent \\",
      '    --fail 2>/dev/null || echo "")',
      '  echo "$token"',
      "}",
      "",
      "# Helper function to call IMDS with v2 token (non-blocking, won't hang)",
      "imds_get() {",
      "  local path=$1",
      "  local token=$(get_imds_token)",
      '  if [ -z "$token" ]; then',
      '    echo ""',
      "    return 1",
      "  fi",
      '  timeout 3 curl -H "X-aws-ec2-metadata-token: $token" \\',
      "    --connect-timeout 2 \\",
      "    --max-time 3 \\",
      "    --silent \\",
      "    --fail \\",
      '    "http://169.254.169.254/latest/$path" 2>/dev/null || echo ""',
      "}",
      "",
      "# Trap to ensure completion marker is always created, even on error",
      "cleanup() {",
      "  EXIT_CODE=$?",
      "  if [ $EXIT_CODE -ne 0 ]; then",
      "    echo 'WARNING: Script exited with error code $EXIT_CODE'",
      "    echo 'Creating completion marker anyway to allow instance to continue...'",
      "  fi",
      "  touch /var/lib/cloud/instance/monitoring-setup-complete || true",
      "  echo '========================================='",
      "  echo 'User data script execution completed'",
      "  echo 'Exit code: $EXIT_CODE'",
      "  echo 'Timestamp:' $(date)",
      "  echo 'Log file: /var/log/user-data.log'",
      "  echo '========================================='",
      "  exit $EXIT_CODE",
      "}",
      "trap cleanup EXIT",
      "",
      `echo '========================================='`,
      `echo 'Monitoring Setup Started - ${envName}'`,
      "echo 'Timestamp:' $(date)",
      `echo '========================================='`,
      "",
      "# ==========================================================================",
      "# SSM AGENT INSTALLATION AND VERIFICATION",
      "# ==========================================================================",
      "echo 'Installing and configuring SSM agent (required for Session Manager)...'",
      "",
      "# Choose package manager (AL2023 uses dnf, AL2 uses yum)",
      "PKG_MGR=yum",
      "command -v dnf >/dev/null 2>&1 && PKG_MGR=dnf",
      "",
      "# Install SSM agent",
      "if $PKG_MGR -y install amazon-ssm-agent; then",
      "  echo '✓ SSM agent installed successfully'",
      "else",
      "  echo 'WARNING: Failed to install SSM agent - will retry'",
      "  $PKG_MGR -y install amazon-ssm-agent || echo 'ERROR: SSM agent installation failed'",
      "fi",
      "",
      "# Enable and start SSM agent",
      "if systemctl enable amazon-ssm-agent; then",
      "  echo '✓ SSM agent enabled'",
      "else",
      "  echo 'WARNING: Failed to enable SSM agent'",
      "fi",
      "",
      "if systemctl start amazon-ssm-agent; then",
      "  echo '✓ SSM agent started'",
      "else",
      "  echo 'WARNING: Failed to start SSM agent immediately - will retry'",
      "  systemctl start amazon-ssm-agent || true",
      "fi",
      "",
      "# Verify SSM agent is running (with retries)",
      "echo 'Verifying SSM agent is running...'",
      "SSM_RETRY_COUNT=0",
      "SSM_MAX_RETRIES=12", // 2 minutes total (10s * 12)
      "while [ $SSM_RETRY_COUNT -lt $SSM_MAX_RETRIES ]; do",
      "  if systemctl is-active amazon-ssm-agent >/dev/null 2>&1; then",
      "    echo '✓ SSM agent is running'",
      "    break",
      "  else",
      "    SSM_RETRY_COUNT=$((SSM_RETRY_COUNT + 1))",
      "    echo \"SSM agent not active yet (attempt $SSM_RETRY_COUNT/$SSM_MAX_RETRIES), waiting 10s...\"",
      "    systemctl start amazon-ssm-agent >/dev/null 2>&1 || true",
      "    sleep 10",
      "  fi",
      "done",
      "",
      "if ! systemctl is-active amazon-ssm-agent >/dev/null 2>&1; then",
      "  echo 'WARNING: SSM agent not active after $SSM_MAX_RETRIES attempts'",
      "  echo '         This may prevent Session Manager access, but instance will continue'",
      "  echo '         SSM agent may start automatically once IAM role is fully attached'",
      "else",
      "  echo '✓ SSM agent is running and ready for Session Manager'",
      "fi",
      ""
    );
  }

  /**
   * EFS mounting and directory setup with enhanced error handling
   */
  private addEfsSetup(props: MonitoringUserDataProps): void {
    this.userDataCommands.push(
      "# ==========================================================================",
      "# EFS SETUP WITH ENHANCED ERROR HANDLING",
      "# ==========================================================================",
      "",
      "echo 'Installing EFS utilities...'",
      "yum update -y",
      "yum install -y amazon-efs-utils awscli",
      "",
      "# Verify installations",
      "aws --version",
      "mount.efs --help >/dev/null 2>&1 && echo '✓ EFS mount helper available'",
      "",
      "# Configure EFS utils",
      "cat > /etc/efs-utils.conf << 'EOF'",
      "[mount]",
      `region = ${props.region}`,
      "iam = true",
      "tls = true",
      "rsize = 1048576",
      "wsize = 1048576",
      "hard = true",
      "intr = true",
      "timeo = 600",
      "retrans = 2",
      "EOF",
      "",
      "# Mount EFS with retry logic",
      "mkdir -p /mnt/efs",
      "MOUNT_RETRIES=5",
      "# Do NOT fail the whole boot if EFS isn't ready yet. We'll retry and continue.",
      "EFS_MOUNTED=false",
      "for i in $(seq 1 $MOUNT_RETRIES); do",
      `  echo "EFS mount attempt $i of $MOUNT_RETRIES"`,
      `  if timeout 90 mount -t efs -o tls,iam ${props.fileSystemId}:/ /mnt/efs; then`,
      "    echo '✓ EFS mounted successfully'",
      "    EFS_MOUNTED=true",
      "    break",
      "  else",
      "    echo 'Mount failed, retrying in 10 seconds...'",
      "    sleep 10",
      "  fi",
      "done",
      "",
      "# Verify EFS mount is working",
      "if ! mountpoint -q /mnt/efs; then",
      "  echo 'WARNING: EFS is not mounted yet. Instance will still register to ECS.'",
      "  echo '         A background retry will continue attempting the mount.'",
      "  (",
      "    for i in $(seq 1 30); do",
      '      echo "Background EFS mount retry $i/30"',
      `      timeout 90 mount -t efs -o tls,iam ${props.fileSystemId}:/ /mnt/efs && break`,
      "      sleep 20",
      "    done",
      "  ) >/var/log/efs-mount-retry.log 2>&1 &",
      "  return",
      "fi",
      "",
      "# Add to fstab for persistence",
      `echo "${props.fileSystemId}:/ /mnt/efs efs defaults,_netdev,tls,iam 0 0" >> /etc/fstab`,
      "",
      "# ==========================================================================",
      "# EFS DIRECTORY STRUCTURE SETUP - USING EXACT WORKING COMMANDS",
      "# ==========================================================================",
      "",
      "echo 'Setting up EFS directory structure using confirmed working commands...'",
      "",
      "# Create directories in EFS (exact commands that worked manually)",
      "sudo mkdir -p /mnt/efs/prometheus-data",
      "sudo mkdir -p /mnt/efs/grafana-data",
      "sudo mkdir -p /mnt/efs/config/prometheus",
      "sudo mkdir -p /mnt/efs/config/grafana/provisioning/datasources",
      "sudo mkdir -p /mnt/efs/config/grafana/provisioning/dashboards",
      "sudo mkdir -p /mnt/efs/config/grafana/dashboards",
      "",
      "# Set base permissions first",
      "sudo chown -R root:root /mnt/efs/",
      "sudo chmod -R 755 /mnt/efs/",
      "",
      "# ==========================================================================",
      "# CONTAINER-SPECIFIC PERMISSIONS FIX",
      "# ==========================================================================",
      "",
      "echo 'Setting container-specific permissions...'",
      "",
      "# Prometheus runs as UID 65534 (nobody) - set ownership for data and config",
      "sudo chown -R 65534:65534 /mnt/efs/prometheus-data",
      "sudo chown -R 65534:65534 /mnt/efs/config/prometheus",
      "sudo chmod -R 755 /mnt/efs/prometheus-data",
      "sudo chmod -R 755 /mnt/efs/config/prometheus",
      "",
      "# Grafana runs as UID 472 (grafana) - set ownership for data and config",
      "sudo chown -R 472:472 /mnt/efs/grafana-data",
      "sudo chown -R 472:472 /mnt/efs/config/grafana",
      "sudo chmod -R 755 /mnt/efs/grafana-data",
      "sudo chmod -R 755 /mnt/efs/config/grafana",
      "",
      "# Ensure Grafana can write to its data directories (some need 777 for plugins/logs)",
      "sudo chmod -R 777 /mnt/efs/grafana-data",
      "",
      "echo '✓ Container-specific permissions set'",
      "echo '✓ EFS directory structure created with working commands'",
      "",
      "# ==========================================================================",
      "# CONFIGURATION FILES - DOWNLOAD FROM SSM (REDUCES USER DATA SIZE)",
      "# ==========================================================================",
      "",
      "echo 'Downloading monitoring configuration files from SSM...'",
      "",
      "# Download Prometheus config from SSM (non-blocking, fallback to basic config)",
      `if aws ssm get-parameter --region ${props.region} --name "/monitoring/${props.efsStackName}/prometheus-config" --query "Parameter.Value" --output text > /tmp/prometheus.yml 2>/dev/null; then`,
      "  echo '✓ Prometheus config downloaded from SSM'",
      "  cp /tmp/prometheus.yml /mnt/efs/config/prometheus/prometheus.yml",
      "  sudo chown 65534:65534 /mnt/efs/config/prometheus/prometheus.yml",
      "else",
      "  echo 'ℹ Creating minimal Prometheus config (SSM not available)'",
      "  cat > /mnt/efs/config/prometheus/prometheus.yml << 'EOF'",
      "global:",
      "  scrape_interval: 15s",
      "  evaluation_interval: 15s",
      "scrape_configs:",
      "  - job_name: 'prometheus'",
      "    metrics_path: /prometheus/metrics",
      "    static_configs:",
      "      - targets: ['localhost:9090']",
      "  - job_name: 'node-exporter'",
      "    static_configs:",
      "      - targets: ['localhost:9100']",
      "EOF",
      "  sudo chown 65534:65534 /mnt/efs/config/prometheus/prometheus.yml",
      "fi",
      "",
      "# Grafana configs are managed by EFS initialization Lambda",
      "echo 'ℹ Grafana configuration managed by EFS Lambda'",
      "",
      "# Verify configuration files",
      "echo 'Verifying configuration files:'",
      "ls -la /mnt/efs/config/prometheus/ || echo 'Config directory not ready yet'",
      "",
      "# ==========================================================================",
      "# CREATE SYMLINKS - USING EXACT WORKING COMMANDS",
      "# ==========================================================================",
      "",
      "echo 'Creating symlinks using confirmed working commands...'",
      "",
      "# Create symlinks (exact commands that worked manually)",
      "sudo ln -sf /mnt/efs/prometheus-data /mnt/prometheus-data",
      "sudo ln -sf /mnt/efs/grafana-data /mnt/grafana-data",
      "sudo ln -sf /mnt/efs/config/prometheus /mnt/prometheus-config",
      "sudo ln -sf /mnt/efs/config/grafana/provisioning /mnt/grafana-provisioning",
      "sudo ln -sf /mnt/efs/config/grafana/dashboards /mnt/grafana-dashboards",
      "",
      "# Verify symlinks were created correctly",
      "echo 'Verifying symlinks:'",
      "ls -la /mnt/ | grep -E '(prometheus|grafana)'",
      "",
      "# Verify EFS directory structure",
      "echo 'Verifying EFS directory structure:'",
      "ls -la /mnt/efs/",
      "ls -la /mnt/efs/config/ 2>/dev/null || echo 'Config directory not found'",
      "",
      "# Final verification - ensure symlinks point to EFS (non-fatal)",
      "# Note: If EFS isn't mounted yet, symlinks may not exist - this is OK, they'll be created later",
      "for link in prometheus-data grafana-data prometheus-config grafana-provisioning grafana-dashboards; do",
      '  if [ -L "/mnt/$link" ]; then',
      '    echo "✓ /mnt/$link -> $(readlink /mnt/$link)"',
      "  else",
      '    echo "WARNING: /mnt/$link is not a symlink (EFS may not be mounted yet - will retry later)"',
      "    # Don't exit - allow script to continue",
      "  fi",
      "done",
      "",
      "echo '✓ EFS setup completed successfully'",
      ""
    );
  }

  /**
   * S3 asset downloads and processing (for ECS stack compatibility)
   */
  private addS3AssetDownloads(props: MonitoringUserDataProps): void {
    if (
      !props.prometheusAsset ||
      !props.grafanaAsset ||
      !props.dashboardsAsset
    ) {
      return;
    }

    this.userDataCommands.push(
      "# ==========================================================================",
      "# S3 ASSET DOWNLOADS",
      "# ==========================================================================",
      "",
      "echo 'Downloading configuration assets from S3...'",
      "",
      "# Download Prometheus config",
      `aws s3 cp s3://${props.prometheusAsset.s3BucketName}/${props.prometheusAsset.s3ObjectKey} /tmp/prometheus-config.zip --region ${props.region}`,
      "unzip -o /tmp/prometheus-config.zip -d /tmp/prometheus-config",
      "",
      "# Download Grafana provisioning",
      `aws s3 cp s3://${props.grafanaAsset.s3BucketName}/${props.grafanaAsset.s3ObjectKey} /tmp/grafana-provisioning.zip --region ${props.region}`,
      "unzip -o /tmp/grafana-provisioning.zip -d /tmp/grafana-provisioning",
      "",
      "# Download Grafana dashboards",
      `aws s3 cp s3://${props.dashboardsAsset.s3BucketName}/${props.dashboardsAsset.s3ObjectKey} /tmp/grafana-dashboards.zip --region ${props.region}`,
      "unzip -o /tmp/grafana-dashboards.zip -d /tmp/grafana-dashboards",
      "",
      "# Process and copy configs",
      "mkdir -p /mnt/prometheus-config /mnt/grafana-provisioning /mnt/grafana-dashboards",
      "",
      "# Copy processed configs to mount points",
      "find /tmp/prometheus-config -name '*.yml' -exec cp {} /mnt/prometheus-config/ \\;",
      "find /tmp/grafana-provisioning -name '*.yml' -exec cp {} /mnt/grafana-provisioning/ \\;",
      "find /tmp/grafana-dashboards -name '*.json' -exec cp {} /mnt/grafana-dashboards/ \\;",
      "",
      "echo '✓ S3 assets processed'",
      ""
    );

    // Add cross-account config injection if provided
    if (props.crossAccountTargets && props.crossAccountTargets.length > 0) {
      this.addCrossAccountConfig(props.crossAccountTargets);
    }
  }

  /**
   * Cross-account monitoring configuration
   */
  private addCrossAccountConfig(targets: CrossAccountTarget[]): void {
    this.userDataCommands.push(
      "# Cross-account monitoring targets",
      "echo 'Configuring cross-account monitoring...'",
      "cat >> /mnt/prometheus-config/prometheus.yml << 'EOF'"
    );

    // Generate Prometheus scrape configs
    targets.forEach((target) => {
      this.userDataCommands.push(
        "",
        `  # ${target.envName} - ${target.targetType}`,
        `  - job_name: '${target.targetType}-${target.envName}'`,
        target.metricsPath ? `    metrics_path: '${target.metricsPath}'` : "",
        "    static_configs:",
        "      - targets:",
        `          - '${target.privateIp}:${target.port}'`,
        "        labels:",
        `          environment: '${target.envName}'`,
        `          service: '${target.targetType}'`,
        "          source: 'cross-account'"
      );
    });

    this.userDataCommands.push(
      "EOF",
      "echo '✓ Cross-account targets configured'",
      ""
    );
  }

  /**
   * ECS agent configuration and startup
   */
  private addEcsConfiguration(clusterName: string): void {
    this.userDataCommands.push(
      "# ==========================================================================",
      "# ECS AGENT CONFIGURATION",
      "# ==========================================================================",
      "",
      "echo 'Configuring ECS agent...'",
      "",
      "# Configure ECS cluster",
      `echo ECS_CLUSTER=${clusterName} >> /etc/ecs/ecs.config`,
      "echo ECS_ENABLE_CONTAINER_METADATA=true >> /etc/ecs/ecs.config",
      "echo ECS_ENABLE_TASK_IAM_ROLE=true >> /etc/ecs/ecs.config",
      "echo ECS_AWSVPC_BLOCK_IMDS=true >> /etc/ecs/ecs.config",
      "",
      "# Security: Block container access to IMDS (best-effort; don't fail boot if tooling differs)",
      "if command -v iptables >/dev/null 2>&1; then",
      "  iptables --insert FORWARD 1 --in-interface docker+ --destination 169.254.169.254/32 --jump DROP || true",
      "fi",
      "if command -v service >/dev/null 2>&1; then",
      "  service iptables save >/dev/null 2>&1 || true",
      "fi",
      "",
      "# CRITICAL: Wait for IAM role to be attached before starting ECS agent",
      "echo 'Waiting for IAM role to be attached...'",
      'IAM_ROLE=""',
      "IAM_WAIT_COUNT=0",
      "IAM_MAX_WAITS=30", // 5 minutes total (10s * 30)
      "while [ $IAM_WAIT_COUNT -lt $IAM_MAX_WAITS ]; do",
      "  IAM_ROLE=$(imds_get meta-data/iam/security-credentials/)",
      '  if [ -n "$IAM_ROLE" ]; then',
      '    echo "✓ IAM role attached: $IAM_ROLE"',
      "    break",
      "  else",
      "    IAM_WAIT_COUNT=$((IAM_WAIT_COUNT + 1))",
      '    echo "Waiting for IAM role (attempt $IAM_WAIT_COUNT/$IAM_MAX_WAITS)..."',
      "    sleep 10",
      "  fi",
      "done",
      "",
      'if [ -z "$IAM_ROLE" ]; then',
      "  echo 'WARNING: IAM role not attached after $IAM_MAX_WAITS attempts'",
      "  echo 'ECS agent will be enabled but may not start until IAM role is attached'",
      "else",
      "  echo '✓ IAM role confirmed attached - proceeding with ECS agent startup'",
      "fi",
      "",
      "# Create systemd service override to add retry logic",
      "echo 'Configuring ECS agent service with retry logic...'",
      "mkdir -p /etc/systemd/system/ecs.service.d",
      "cat > /etc/systemd/system/ecs.service.d/override.conf << 'EOF'",
      "[Service]",
      "# Restart ECS agent if it fails (wait 30s between retries)",
      "Restart=on-failure",
      "RestartSec=30",
      "# Keep retrying for up to 10 minutes",
      "StartLimitInterval=600",
      "StartLimitBurst=20",
      "EOF",
      "",
      "# Reload systemd to pick up the override",
      "systemctl daemon-reload",
      "",
      "# Enable ECS agent service (always do this)",
      "echo 'Enabling ECS agent service...'",
      "systemctl enable ecs || echo 'WARNING: Failed to enable ECS service'",
      "",
      "# Start ECS agent (now that IAM role should be attached)",
      "echo 'Starting ECS agent...'",
      "if systemctl start ecs; then",
      "  echo '✓ ECS agent started successfully'",
      "else",
      "  echo 'WARNING: Failed to start ECS agent immediately'",
      "  echo 'Checking ECS agent logs for errors...'",
      "  if [ -f /var/log/ecs/ecs-agent.log ]; then",
      "    echo 'Last 20 lines of ECS agent log:'",
      "    tail -20 /var/log/ecs/ecs-agent.log || true",
      "  else",
      "    echo 'ECS agent log file does not exist yet'",
      "  fi",
      "  echo 'Will retry starting ECS agent below...'",
      "fi",
      "",
      "# Verify ECS agent is running (with retries)",
      "echo 'Verifying ECS agent is running...'",
      "RETRY_COUNT=0",
      "MAX_RETRIES=18", // 3 minutes total (10s * 18)
      "while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do",
      "  if systemctl is-active ecs >/dev/null 2>&1; then",
      "    echo '✓ ECS agent is running'",
      "    # Verify it's actually working by checking the log",
      "    if [ -f /var/log/ecs/ecs-agent.log ]; then",
      "      if grep -q 'Registered container instance' /var/log/ecs/ecs-agent.log 2>/dev/null; then",
      "        echo '✓ ECS agent has registered with cluster'",
      "      elif grep -q 'Error\\|Failed\\|Fatal' /var/log/ecs/ecs-agent.log 2>/dev/null; then",
      "        echo '⚠️  ECS agent log contains errors - checking details...'",
      "        grep -i 'error\\|failed\\|fatal' /var/log/ecs/ecs-agent.log | tail -5 || true",
      "      else",
      "        echo 'ℹ️  ECS agent is running but may still be initializing'",
      "      fi",
      "    fi",
      "    break",
      "  else",
      "    RETRY_COUNT=$((RETRY_COUNT + 1))",
      '    echo "ECS agent not active yet (attempt $RETRY_COUNT/$MAX_RETRIES), waiting 10s..."',
      "    # Try to start it again (in case IAM role was just attached)",
      "    systemctl start ecs >/dev/null 2>&1 || true",
      "    sleep 10",
      "  fi",
      "done",
      "",
      "# Final check and diagnostics",
      "if ! systemctl is-active ecs >/dev/null 2>&1; then",
      "  echo '❌ ECS agent not active after $MAX_RETRIES attempts'",
      "  echo ''",
      "  echo 'DIAGNOSTICS:'",
      "  echo '============'",
      "  echo '1. Checking IAM role:'",
      "  IAM_ROLE_CHECK=$(imds_get meta-data/iam/security-credentials/ 2>/dev/null || echo '')",
      '  if [ -n "$IAM_ROLE_CHECK" ]; then',
      '    echo "   ✓ IAM role is attached: $IAM_ROLE_CHECK"',
      "  else",
      "    echo '   ❌ IAM role is NOT attached - this is likely the problem!'",
      "  fi",
      "  echo ''",
      "  echo '2. Checking ECS agent logs:'",
      "  if [ -f /var/log/ecs/ecs-agent.log ]; then",
      "    echo '   Last 30 lines of ECS agent log:'",
      "    tail -30 /var/log/ecs/ecs-agent.log | sed 's/^/   /' || true",
      "  else",
      "    echo '   ❌ ECS agent log file does not exist'",
      "  fi",
      "  echo ''",
      "  echo '3. Checking ECS config:'",
      "  if [ -f /etc/ecs/ecs.config ]; then",
      "    echo '   ECS configuration:'",
      "    cat /etc/ecs/ecs.config | sed 's/^/   /' || true",
      "  else",
      "    echo '   ❌ ECS config file does not exist'",
      "  fi",
      "  echo ''",
      "  echo '4. Checking systemd service status:'",
      "  systemctl status ecs --no-pager -l | head -20 | sed 's/^/   /' || true",
      "  echo ''",
      "  echo 'The instance will continue setup - ECS agent may start after IAM role is attached'",
      "  echo 'You can manually start it later with: sudo systemctl start ecs'",
      "else",
      "  echo '✓ ECS agent verified running and healthy'",
      "fi",
      ""
    );
  }

  /**
   * Script footer with completion marker
   */
  private addScriptFooter(): void {
    this.userDataCommands.push(
      "# ==========================================================================",
      "# SETUP COMPLETION",
      "# ==========================================================================",
      "",
      "# Create completion marker (trap will also create this on exit, but create it here too)",
      "touch /var/lib/cloud/instance/monitoring-setup-complete || true",
      "",
      "echo '========================================='",
      "echo '✓ Monitoring setup completed successfully!'",
      "echo 'Timestamp:' $(date)",
      "echo 'Log file: /var/log/user-data.log'",
      "echo '========================================='",
      ""
    );
  }
}
